#! /bin/bash
CWD=~/TechRep/programming18/git/trace-expressions/examples/express-examples/fileExplorer
for i in `seq 1 10`
do node $CWD/simple_server.js &
sleep 5
node $CWD/benchmark-client.js $1 >> $CWD/results-original.txt
pkill node   
sleep 5
done
