#! /bin/bash
#CWD=~/TechRep/programming18/git/trace-expressions/examples/express-examples/helloWorld
CWD=.
for i in `seq 1 10`
do node $CWD/hello_world.js &
sleep 5
node $CWD/benchmark-client.js $1 >> $CWD/results-original.txt
pkill node   
sleep 5
done
